### PR TITLE
Attempt to fix /f chat

### PR DESCRIPTION
**Pull request by corytortoise**
Currently, /f chat and /f allychat don't work. This should fix it. I have not tested this, however.

### CODE REVIEW

**Comment by iChaoticSoldier** [comment]
Deleting those will caused an error to a console

**Comment by corytortoise** [comment]
What error?

**Comment by corytortoise** [comment]
Closing due to f chat being disabled deliberately.

**Comment by iChaoticSoldier** [comment]
Console error like it will disable the plugin due to error

**Comment by Awzaw** [comment]
I've added a config option to enable or disable chat: https://poggit.pmmp.io/p/FactionsPro

**Comment by iChaoticSoldier** [comment]
Awzaw how about the faction chat format? Like when u did /f chat then you type message it will be like this  [TEST] xXCreepsXx > {msg} make a config called ChatFormat so we can edit the format message for faction chat

**Pull request closed without merging**
